// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: simple.proto

package pbmo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 基础枚举类型
type Status int32

const (
	Status_STATUS_UNKNOWN  Status = 0
	Status_STATUS_ACTIVE   Status = 1
	Status_STATUS_INACTIVE Status = 2
	Status_STATUS_PENDING  Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
		3: "STATUS_PENDING",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":  0,
		"STATUS_ACTIVE":   1,
		"STATUS_INACTIVE": 2,
		"STATUS_PENDING":  3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_simple_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_simple_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{0}
}

type Priority int32

const (
	Priority_PRIORITY_LOW      Priority = 0
	Priority_PRIORITY_MEDIUM   Priority = 1
	Priority_PRIORITY_HIGH     Priority = 2
	Priority_PRIORITY_CRITICAL Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_LOW",
		1: "PRIORITY_MEDIUM",
		2: "PRIORITY_HIGH",
		3: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_LOW":      0,
		"PRIORITY_MEDIUM":   1,
		"PRIORITY_HIGH":     2,
		"PRIORITY_CRITICAL": 3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_simple_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_simple_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{1}
}

// 嵌套消息类型
type Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"street" gorm:"column:street" validate:"required"
	Street string `protobuf:"bytes,1,opt,name=street,proto3" json:"street" gorm:"column:street" validate:"required"`
	// @inject_tag: json:"city" gorm:"column:city" validate:"required"
	City string `protobuf:"bytes,2,opt,name=city,proto3" json:"city" gorm:"column:city" validate:"required"`
	// @inject_tag: json:"country" gorm:"column:country" validate:"required"
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country" gorm:"column:country" validate:"required"`
	// @inject_tag: json:"postal_code" gorm:"column:postal_code" validate:"required"
	PostalCode    string `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code" gorm:"column:postal_code" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type Contact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"email" gorm:"column:email" validate:"email"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email" gorm:"column:email" validate:"email"`
	// @inject_tag: json:"phone" gorm:"column:phone" validate:"required"
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone" gorm:"column:phone" validate:"required"`
	// @inject_tag: json:"website" gorm:"column:website"
	Website       string `protobuf:"bytes,3,opt,name=website,proto3" json:"website" gorm:"column:website"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{1}
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Contact) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

// 主要消息类型 - 覆盖所有基础类型
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数值类型
	// @inject_tag: json:"id" gorm:"primaryKey;column:id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"primaryKey;column:id"`
	// @inject_tag: json:"age" gorm:"column:age" validate:"min=0,max=150"
	Age int32 `protobuf:"varint,2,opt,name=age,proto3" json:"age" gorm:"column:age" validate:"min=0,max=150"`
	// @inject_tag: json:"score" gorm:"column:score"
	Score uint32 `protobuf:"varint,3,opt,name=score,proto3" json:"score" gorm:"column:score"`
	// @inject_tag: json:"balance" gorm:"column:balance;type:decimal(10,2)"
	Balance uint64 `protobuf:"varint,4,opt,name=balance,proto3" json:"balance" gorm:"column:balance;type:decimal(10,2)"`
	// @inject_tag: json:"rating" gorm:"column:rating"
	Rating float32 `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating" gorm:"column:rating"`
	// @inject_tag: json:"salary" gorm:"column:salary;type:decimal(15,2)"
	Salary float64 `protobuf:"fixed64,6,opt,name=salary,proto3" json:"salary" gorm:"column:salary;type:decimal(15,2)"`
	// 字符串类型
	// @inject_tag: json:"name" gorm:"column:name" validate:"required,min=2,max=50"
	Name string `protobuf:"bytes,7,opt,name=name,proto3" json:"name" gorm:"column:name" validate:"required,min=2,max=50"`
	// @inject_tag: json:"username" gorm:"column:username;unique" validate:"required,alphanum"
	Username string `protobuf:"bytes,8,opt,name=username,proto3" json:"username" gorm:"column:username;unique" validate:"required,alphanum"`
	// @inject_tag: json:"bio" gorm:"column:bio;type:text"
	Bio string `protobuf:"bytes,9,opt,name=bio,proto3" json:"bio" gorm:"column:bio;type:text"`
	// 布尔类型
	// @inject_tag: json:"is_active" gorm:"column:is_active;default:true"
	IsActive bool `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active" gorm:"column:is_active;default:true"`
	// @inject_tag: json:"is_verified" gorm:"column:is_verified;default:false"
	IsVerified bool `protobuf:"varint,11,opt,name=is_verified,json=isVerified,proto3" json:"is_verified" gorm:"column:is_verified;default:false"`
	// 字节类型
	// @inject_tag: json:"avatar" gorm:"column:avatar;type:blob"
	Avatar []byte `protobuf:"bytes,12,opt,name=avatar,proto3" json:"avatar" gorm:"column:avatar;type:blob"`
	// @inject_tag: json:"signature" gorm:"column:signature"
	Signature []byte `protobuf:"bytes,13,opt,name=signature,proto3" json:"signature" gorm:"column:signature"`
	// 枚举类型
	// @inject_tag: json:"status" gorm:"column:status;type:int" validate:"required"
	Status Status `protobuf:"varint,14,opt,name=status,proto3,enum=pbmo.Status" json:"status" gorm:"column:status;type:int" validate:"required"`
	// @inject_tag: json:"priority" gorm:"column:priority;type:int"
	Priority Priority `protobuf:"varint,15,opt,name=priority,proto3,enum=pbmo.Priority" json:"priority" gorm:"column:priority;type:int"`
	// 嵌套消息类型
	// @inject_tag: json:"address" gorm:"embedded;embeddedPrefix:address_"
	Address *Address `protobuf:"bytes,16,opt,name=address,proto3" json:"address" gorm:"embedded;embeddedPrefix:address_"`
	// @inject_tag: json:"contact" gorm:"embedded;embeddedPrefix:contact_"
	Contact *Contact `protobuf:"bytes,17,opt,name=contact,proto3" json:"contact" gorm:"embedded;embeddedPrefix:contact_"`
	// 重复字段（数组/切片）
	// @inject_tag: json:"tags" gorm:"type:json"
	Tags []string `protobuf:"bytes,18,rep,name=tags,proto3" json:"tags" gorm:"type:json"`
	// @inject_tag: json:"scores" gorm:"type:json"
	Scores []int32 `protobuf:"varint,19,rep,packed,name=scores,proto3" json:"scores" gorm:"type:json"`
	// @inject_tag: json:"preferences" gorm:"type:json"
	Preferences []bool `protobuf:"varint,20,rep,packed,name=preferences,proto3" json:"preferences" gorm:"type:json"`
	// 可选字段
	// @inject_tag: json:"nickname,omitempty" gorm:"column:nickname"
	Nickname *string `protobuf:"bytes,21,opt,name=nickname,proto3,oneof" json:"nickname,omitempty" gorm:"column:nickname"`
	// @inject_tag: json:"middle_age,omitempty" gorm:"column:middle_age"
	MiddleAge *int32 `protobuf:"varint,22,opt,name=middle_age,json=middleAge,proto3,oneof" json:"middle_age,omitempty" gorm:"column:middle_age"`
	// @inject_tag: json:"is_premium,omitempty" gorm:"column:is_premium"
	IsPremium *bool `protobuf:"varint,23,opt,name=is_premium,json=isPremium,proto3,oneof" json:"is_premium,omitempty" gorm:"column:is_premium"`
	// Map类型
	// @inject_tag: json:"metadata" gorm:"type:json"
	Metadata map[string]string `protobuf:"bytes,24,rep,name=metadata,proto3" json:"metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" gorm:"type:json"`
	// @inject_tag: json:"settings" gorm:"type:json"
	Settings map[string]int32 `protobuf:"bytes,25,rep,name=settings,proto3" json:"settings" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value" gorm:"type:json"`
	// @inject_tag: json:"flags" gorm:"type:json"
	Flags         map[string]bool `protobuf:"bytes,26,rep,name=flags,proto3" json:"flags" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value" gorm:"type:json"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_simple_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *User) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *User) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *User) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *User) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *User) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *User) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *User) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_LOW
}

func (x *User) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *User) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *User) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User) GetScores() []int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *User) GetPreferences() []bool {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *User) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *User) GetMiddleAge() int32 {
	if x != nil && x.MiddleAge != nil {
		return *x.MiddleAge
	}
	return 0
}

func (x *User) GetIsPremium() bool {
	if x != nil && x.IsPremium != nil {
		return *x.IsPremium
	}
	return false
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetSettings() map[string]int32 {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *User) GetFlags() map[string]bool {
	if x != nil {
		return x.Flags
	}
	return nil
}

// 产品消息 - 更多类型示例
type Product struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id" gorm:"primaryKey;column:id"
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"primaryKey;column:id"`
	// @inject_tag: json:"name" gorm:"column:name" validate:"required"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" gorm:"column:name" validate:"required"`
	// @inject_tag: json:"price" gorm:"column:price;type:decimal(10,2)" validate:"min=0"
	Price float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price" gorm:"column:price;type:decimal(10,2)" validate:"min=0"`
	// @inject_tag: json:"in_stock" gorm:"column:in_stock;default:true"
	InStock bool `protobuf:"varint,4,opt,name=in_stock,json=inStock,proto3" json:"in_stock" gorm:"column:in_stock;default:true"`
	// @inject_tag: json:"category" gorm:"column:category;type:int"
	Category Status `protobuf:"varint,5,opt,name=category,proto3,enum=pbmo.Status" json:"category" gorm:"column:category;type:int"`
	// @inject_tag: json:"images" gorm:"type:json"
	Images []string `protobuf:"bytes,6,rep,name=images,proto3" json:"images" gorm:"type:json"`
	// @inject_tag: json:"properties" gorm:"type:json"
	Properties map[string]string `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" gorm:"type:json"`
	// @inject_tag: json:"description,omitempty" gorm:"column:description;type:text"
	Description   *string `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty" gorm:"column:description;type:text"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_simple_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{3}
}

func (x *Product) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *Product) GetCategory() Status {
	if x != nil {
		return x.Category
	}
	return Status_STATUS_UNKNOWN
}

func (x *Product) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Product) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// 订单消息 - 展示关联关系
type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id" gorm:"primaryKey;column:id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"primaryKey;column:id"`
	// @inject_tag: json:"user_id" gorm:"column:user_id" validate:"required"
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id" gorm:"column:user_id" validate:"required"`
	// @inject_tag: json:"total" gorm:"column:total;type:decimal(10,2)"
	Total float64 `protobuf:"fixed64,3,opt,name=total,proto3" json:"total" gorm:"column:total;type:decimal(10,2)"`
	// @inject_tag: json:"status" gorm:"column:status;type:int"
	Status Status `protobuf:"varint,4,opt,name=status,proto3,enum=pbmo.Status" json:"status" gorm:"column:status;type:int"`
	// @inject_tag: json:"items" gorm:"type:json"
	Items []*Product `protobuf:"bytes,5,rep,name=items,proto3" json:"items" gorm:"type:json"`
	// @inject_tag: json:"shipping_address" gorm:"embedded;embeddedPrefix:shipping_"
	ShippingAddress *Address `protobuf:"bytes,6,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address" gorm:"embedded;embeddedPrefix:shipping_"`
	// @inject_tag: json:"notes" gorm:"type:json"
	Notes         map[string]string `protobuf:"bytes,7,rep,name=notes,proto3" json:"notes" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" gorm:"type:json"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_simple_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *Order) GetItems() []*Product {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *Order) GetNotes() map[string]string {
	if x != nil {
		return x.Notes
	}
	return nil
}

// 响应消息类型
type UserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// @inject_tag: json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	// @inject_tag: json:"user,omitempty"
	User *User `protobuf:"bytes,3,opt,name=user,proto3,oneof" json:"user,omitempty"`
	// @inject_tag: json:"users"
	Users []*User `protobuf:"bytes,4,rep,name=users,proto3" json:"users"`
	// @inject_tag: json:"total_count"
	TotalCount    int32 `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_simple_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 请求消息类型
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id" validate:"required,min=1"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" validate:"required,min=1"`
	// @inject_tag: json:"include_inactive,omitempty"
	IncludeInactive *bool `protobuf:"varint,2,opt,name=include_inactive,json=includeInactive,proto3,oneof" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_simple_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserRequest) GetIncludeInactive() bool {
	if x != nil && x.IncludeInactive != nil {
		return *x.IncludeInactive
	}
	return false
}

type ListUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"page" validate:"min=1"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page" validate:"min=1"`
	// @inject_tag: json:"page_size" validate:"min=1,max=100"
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size" validate:"min=1,max=100"`
	// @inject_tag: json:"status,omitempty"
	Status *Status `protobuf:"varint,3,opt,name=status,proto3,enum=pbmo.Status,oneof" json:"status,omitempty"`
	// @inject_tag: json:"search,omitempty"
	Search *string `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	// @inject_tag: json:"filters"
	Filters       map[string]string `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_simple_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetStatus() Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *ListUsersRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListUsersRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

var File_simple_proto protoreflect.FileDescriptor

const file_simple_proto_rawDesc = "" +
	"\n" +
	"\fsimple.proto\x12\x04pbmo\"p\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x04 \x01(\tR\n" +
	"postalCode\"O\n" +
	"\aContact\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x18\n" +
	"\awebsite\x18\x03 \x01(\tR\awebsite\"\x91\b\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x14\n" +
	"\x05score\x18\x03 \x01(\rR\x05score\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x04R\abalance\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x02R\x06rating\x12\x16\n" +
	"\x06salary\x18\x06 \x01(\x01R\x06salary\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\t \x01(\tR\x03bio\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12\x1f\n" +
	"\vis_verified\x18\v \x01(\bR\n" +
	"isVerified\x12\x16\n" +
	"\x06avatar\x18\f \x01(\fR\x06avatar\x12\x1c\n" +
	"\tsignature\x18\r \x01(\fR\tsignature\x12$\n" +
	"\x06status\x18\x0e \x01(\x0e2\f.pbmo.StatusR\x06status\x12*\n" +
	"\bpriority\x18\x0f \x01(\x0e2\x0e.pbmo.PriorityR\bpriority\x12'\n" +
	"\aaddress\x18\x10 \x01(\v2\r.pbmo.AddressR\aaddress\x12'\n" +
	"\acontact\x18\x11 \x01(\v2\r.pbmo.ContactR\acontact\x12\x12\n" +
	"\x04tags\x18\x12 \x03(\tR\x04tags\x12\x16\n" +
	"\x06scores\x18\x13 \x03(\x05R\x06scores\x12 \n" +
	"\vpreferences\x18\x14 \x03(\bR\vpreferences\x12\x1f\n" +
	"\bnickname\x18\x15 \x01(\tH\x00R\bnickname\x88\x01\x01\x12\"\n" +
	"\n" +
	"middle_age\x18\x16 \x01(\x05H\x01R\tmiddleAge\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_premium\x18\x17 \x01(\bH\x02R\tisPremium\x88\x01\x01\x124\n" +
	"\bmetadata\x18\x18 \x03(\v2\x18.pbmo.User.MetadataEntryR\bmetadata\x124\n" +
	"\bsettings\x18\x19 \x03(\v2\x18.pbmo.User.SettingsEntryR\bsettings\x12+\n" +
	"\x05flags\x18\x1a \x03(\v2\x15.pbmo.User.FlagsEntryR\x05flags\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B\v\n" +
	"\t_nicknameB\r\n" +
	"\v_middle_ageB\r\n" +
	"\v_is_premium\"\xd5\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x19\n" +
	"\bin_stock\x18\x04 \x01(\bR\ainStock\x12(\n" +
	"\bcategory\x18\x05 \x01(\x0e2\f.pbmo.StatusR\bcategory\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\x12=\n" +
	"\n" +
	"properties\x18\a \x03(\v2\x1d.pbmo.Product.PropertiesEntryR\n" +
	"properties\x12%\n" +
	"\vdescription\x18\b \x01(\tH\x00R\vdescription\x88\x01\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_description\"\xb3\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x01R\x05total\x12$\n" +
	"\x06status\x18\x04 \x01(\x0e2\f.pbmo.StatusR\x06status\x12#\n" +
	"\x05items\x18\x05 \x03(\v2\r.pbmo.ProductR\x05items\x128\n" +
	"\x10shipping_address\x18\x06 \x01(\v2\r.pbmo.AddressR\x0fshippingAddress\x12,\n" +
	"\x05notes\x18\a \x03(\v2\x16.pbmo.Order.NotesEntryR\x05notes\x1a8\n" +
	"\n" +
	"NotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\fUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04user\x18\x03 \x01(\v2\n" +
	".pbmo.UserH\x00R\x04user\x88\x01\x01\x12 \n" +
	"\x05users\x18\x04 \x03(\v2\n" +
	".pbmo.UserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x05 \x01(\x05R\n" +
	"totalCountB\a\n" +
	"\x05_user\"e\n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x10include_inactive\x18\x02 \x01(\bH\x00R\x0fincludeInactive\x88\x01\x01B\x13\n" +
	"\x11_include_inactive\"\x9c\x02\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\f.pbmo.StatusH\x00R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x01R\x06search\x88\x01\x01\x12=\n" +
	"\afilters\x18\x05 \x03(\v2#.pbmo.ListUsersRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_statusB\t\n" +
	"\a_search*X\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x03*[\n" +
	"\bPriority\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x00\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x01\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x02\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x03B\tZ\a./;pbmob\x06proto3"

var (
	file_simple_proto_rawDescOnce sync.Once
	file_simple_proto_rawDescData []byte
)

func file_simple_proto_rawDescGZIP() []byte {
	file_simple_proto_rawDescOnce.Do(func() {
		file_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simple_proto_rawDesc), len(file_simple_proto_rawDesc)))
	})
	return file_simple_proto_rawDescData
}

var file_simple_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_simple_proto_goTypes = []any{
	(Status)(0),              // 0: pbmo.Status
	(Priority)(0),            // 1: pbmo.Priority
	(*Address)(nil),          // 2: pbmo.Address
	(*Contact)(nil),          // 3: pbmo.Contact
	(*User)(nil),             // 4: pbmo.User
	(*Product)(nil),          // 5: pbmo.Product
	(*Order)(nil),            // 6: pbmo.Order
	(*UserResponse)(nil),     // 7: pbmo.UserResponse
	(*GetUserRequest)(nil),   // 8: pbmo.GetUserRequest
	(*ListUsersRequest)(nil), // 9: pbmo.ListUsersRequest
	nil,                      // 10: pbmo.User.MetadataEntry
	nil,                      // 11: pbmo.User.SettingsEntry
	nil,                      // 12: pbmo.User.FlagsEntry
	nil,                      // 13: pbmo.Product.PropertiesEntry
	nil,                      // 14: pbmo.Order.NotesEntry
	nil,                      // 15: pbmo.ListUsersRequest.FiltersEntry
}
var file_simple_proto_depIdxs = []int32{
	0,  // 0: pbmo.User.status:type_name -> pbmo.Status
	1,  // 1: pbmo.User.priority:type_name -> pbmo.Priority
	2,  // 2: pbmo.User.address:type_name -> pbmo.Address
	3,  // 3: pbmo.User.contact:type_name -> pbmo.Contact
	10, // 4: pbmo.User.metadata:type_name -> pbmo.User.MetadataEntry
	11, // 5: pbmo.User.settings:type_name -> pbmo.User.SettingsEntry
	12, // 6: pbmo.User.flags:type_name -> pbmo.User.FlagsEntry
	0,  // 7: pbmo.Product.category:type_name -> pbmo.Status
	13, // 8: pbmo.Product.properties:type_name -> pbmo.Product.PropertiesEntry
	0,  // 9: pbmo.Order.status:type_name -> pbmo.Status
	5,  // 10: pbmo.Order.items:type_name -> pbmo.Product
	2,  // 11: pbmo.Order.shipping_address:type_name -> pbmo.Address
	14, // 12: pbmo.Order.notes:type_name -> pbmo.Order.NotesEntry
	4,  // 13: pbmo.UserResponse.user:type_name -> pbmo.User
	4,  // 14: pbmo.UserResponse.users:type_name -> pbmo.User
	0,  // 15: pbmo.ListUsersRequest.status:type_name -> pbmo.Status
	15, // 16: pbmo.ListUsersRequest.filters:type_name -> pbmo.ListUsersRequest.FiltersEntry
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_simple_proto_init() }
func file_simple_proto_init() {
	if File_simple_proto != nil {
		return
	}
	file_simple_proto_msgTypes[2].OneofWrappers = []any{}
	file_simple_proto_msgTypes[3].OneofWrappers = []any{}
	file_simple_proto_msgTypes[5].OneofWrappers = []any{}
	file_simple_proto_msgTypes[6].OneofWrappers = []any{}
	file_simple_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simple_proto_rawDesc), len(file_simple_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simple_proto_goTypes,
		DependencyIndexes: file_simple_proto_depIdxs,
		EnumInfos:         file_simple_proto_enumTypes,
		MessageInfos:      file_simple_proto_msgTypes,
	}.Build()
	File_simple_proto = out.File
	file_simple_proto_goTypes = nil
	file_simple_proto_depIdxs = nil
}
