// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: github.com/Divine-Dragon-Voyage/engine-access-control-service/pb/engine-access-control-service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessControlService_DictNew_FullMethodName                    = "/ddv.access_control.api.AccessControlService/DictNew"
	AccessControlService_DictList_FullMethodName                   = "/ddv.access_control.api.AccessControlService/DictList"
	AccessControlService_DictGet_FullMethodName                    = "/ddv.access_control.api.AccessControlService/DictGet"
	AccessControlService_DictUpdate_FullMethodName                 = "/ddv.access_control.api.AccessControlService/DictUpdate"
	AccessControlService_DictDelete_FullMethodName                 = "/ddv.access_control.api.AccessControlService/DictDelete"
	AccessControlService_OplogNew_FullMethodName                   = "/ddv.access_control.api.AccessControlService/OplogNew"
	AccessControlService_OplogList_FullMethodName                  = "/ddv.access_control.api.AccessControlService/OplogList"
	AccessControlService_OplogGet_FullMethodName                   = "/ddv.access_control.api.AccessControlService/OplogGet"
	AccessControlService_OplogDelete_FullMethodName                = "/ddv.access_control.api.AccessControlService/OplogDelete"
	AccessControlService_BucketList_FullMethodName                 = "/ddv.access_control.api.AccessControlService/BucketList"
	AccessControlService_BucketNew_FullMethodName                  = "/ddv.access_control.api.AccessControlService/BucketNew"
	AccessControlService_BucketDelete_FullMethodName               = "/ddv.access_control.api.AccessControlService/BucketDelete"
	AccessControlService_ObjectList_FullMethodName                 = "/ddv.access_control.api.AccessControlService/ObjectList"
	AccessControlService_ObjectGet_FullMethodName                  = "/ddv.access_control.api.AccessControlService/ObjectGet"
	AccessControlService_ObjectPut_FullMethodName                  = "/ddv.access_control.api.AccessControlService/ObjectPut"
	AccessControlService_ObjectDelete_FullMethodName               = "/ddv.access_control.api.AccessControlService/ObjectDelete"
	AccessControlService_ObjectPresignedDownloadUrl_FullMethodName = "/ddv.access_control.api.AccessControlService/ObjectPresignedDownloadUrl"
	AccessControlService_ObjectPresignedUploadUrl_FullMethodName   = "/ddv.access_control.api.AccessControlService/ObjectPresignedUploadUrl"
	AccessControlService_Install_FullMethodName                    = "/ddv.access_control.api.AccessControlService/Install"
	AccessControlService_Endpoints_FullMethodName                  = "/ddv.access_control.api.AccessControlService/Endpoints"
	AccessControlService_SendCode_FullMethodName                   = "/ddv.access_control.api.AccessControlService/SendCode"
	AccessControlService_RegisterCheck_FullMethodName              = "/ddv.access_control.api.AccessControlService/RegisterCheck"
	AccessControlService_Register_FullMethodName                   = "/ddv.access_control.api.AccessControlService/Register"
	AccessControlService_Login_FullMethodName                      = "/ddv.access_control.api.AccessControlService/Login"
	AccessControlService_RefreshToken_FullMethodName               = "/ddv.access_control.api.AccessControlService/RefreshToken"
	AccessControlService_Authorities_FullMethodName                = "/ddv.access_control.api.AccessControlService/Authorities"
	AccessControlService_UserInfo_FullMethodName                   = "/ddv.access_control.api.AccessControlService/UserInfo"
	AccessControlService_UserMenusTree_FullMethodName              = "/ddv.access_control.api.AccessControlService/UserMenusTree"
	AccessControlService_Logout_FullMethodName                     = "/ddv.access_control.api.AccessControlService/Logout"
	AccessControlService_UserList_FullMethodName                   = "/ddv.access_control.api.AccessControlService/UserList"
	AccessControlService_UserGet_FullMethodName                    = "/ddv.access_control.api.AccessControlService/UserGet"
	AccessControlService_UserNew_FullMethodName                    = "/ddv.access_control.api.AccessControlService/UserNew"
	AccessControlService_UserDelete_FullMethodName                 = "/ddv.access_control.api.AccessControlService/UserDelete"
	AccessControlService_UserUpdate_FullMethodName                 = "/ddv.access_control.api.AccessControlService/UserUpdate"
	AccessControlService_UserChangePassword_FullMethodName         = "/ddv.access_control.api.AccessControlService/UserChangePassword"
	AccessControlService_UserResetPassword_FullMethodName          = "/ddv.access_control.api.AccessControlService/UserResetPassword"
	AccessControlService_RoleNew_FullMethodName                    = "/ddv.access_control.api.AccessControlService/RoleNew"
	AccessControlService_RoleList_FullMethodName                   = "/ddv.access_control.api.AccessControlService/RoleList"
	AccessControlService_RoleGet_FullMethodName                    = "/ddv.access_control.api.AccessControlService/RoleGet"
	AccessControlService_RoleUpdate_FullMethodName                 = "/ddv.access_control.api.AccessControlService/RoleUpdate"
	AccessControlService_RoleDelete_FullMethodName                 = "/ddv.access_control.api.AccessControlService/RoleDelete"
	AccessControlService_MenuNew_FullMethodName                    = "/ddv.access_control.api.AccessControlService/MenuNew"
	AccessControlService_MenuList_FullMethodName                   = "/ddv.access_control.api.AccessControlService/MenuList"
	AccessControlService_MenuTree_FullMethodName                   = "/ddv.access_control.api.AccessControlService/MenuTree"
	AccessControlService_MenuGet_FullMethodName                    = "/ddv.access_control.api.AccessControlService/MenuGet"
	AccessControlService_MenuUpdate_FullMethodName                 = "/ddv.access_control.api.AccessControlService/MenuUpdate"
	AccessControlService_MenuDelete_FullMethodName                 = "/ddv.access_control.api.AccessControlService/MenuDelete"
)

// AccessControlServiceClient is the client API for AccessControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessControlServiceClient interface {
	// 创建字典 [SINCE v0.1.0].
	// [EN] Create a dict [SINCE v0.1.0].
	DictNew(ctx context.Context, in *DictNewRequest, opts ...grpc.CallOption) (*DictNewResponse, error)
	// 列出字典列表 [SINCE v0.1.0].
	// [EN] List dicts [SINCE v0.1.0].
	DictList(ctx context.Context, in *DictListRequest, opts ...grpc.CallOption) (*DictListResponse, error)
	// 获取指定字典 [SINCE v0.1.0].
	// [EN] Get the specified dict information [SINCE v0.1.0].
	DictGet(ctx context.Context, in *DictGetRequest, opts ...grpc.CallOption) (*DictGetResponse, error)
	// 更新指定字典信息 [SINCE v0.1.0].
	// [EN] Update information of the specified dict [SINCE v0.1.0].
	DictUpdate(ctx context.Context, in *DictUpdateRequest, opts ...grpc.CallOption) (*DictUpdateResponse, error)
	// 删除指定字典 [SINCE v0.1.0].
	// [EN] Delete dict [SINCE v0.1.0].
	DictDelete(ctx context.Context, in *DictDeleteRequest, opts ...grpc.CallOption) (*DictDeleteResponse, error)
	// 写入操作日志 [SINCE v0.1.0].
	// [EN] Write operation log [SINCE v0.1.0].
	OplogNew(ctx context.Context, in *OplogNewRequest, opts ...grpc.CallOption) (*OplogNewResponse, error)
	// 列出操作日志列表 [SINCE v0.1.0].
	// [EN] Lists operation log list [SINCE v0.1.0].
	OplogList(ctx context.Context, in *OplogListRequest, opts ...grpc.CallOption) (*OplogListResponse, error)
	// 获取指定操作日志信息 [SINCE v0.1.0].
	// [EN] Gets specified operation log information [SINCE v0.1.0].
	OplogGet(ctx context.Context, in *OplogGetRequest, opts ...grpc.CallOption) (*OplogGetResponse, error)
	// 删除指定操作日志 [SINCE v0.1.0].
	// [EN] Delete oplog [SINCE v0.1.0].
	OplogDelete(ctx context.Context, in *OplogDeleteRequest, opts ...grpc.CallOption) (*OplogDeleteResponse, error)
	// 列出当前所有Bucket空间.
	// [EN] Lists all current Bucket Spaces.
	BucketList(ctx context.Context, in *BucketListRequest, opts ...grpc.CallOption) (*BucketListResponse, error)
	// 创建Bucket空间.
	// [EN] Deletes bucket.
	BucketNew(ctx context.Context, in *BucketNewRequest, opts ...grpc.CallOption) (*BucketNewResponse, error)
	// 删除Bucket空间.
	// [EN] Deletes bucket.
	BucketDelete(ctx context.Context, in *BucketDeleteRequest, opts ...grpc.CallOption) (*BucketDeleteResponse, error)
	// 列出Object对象列表.
	// [EN] Lists objects.
	ObjectList(ctx context.Context, in *ObjectListRequest, opts ...grpc.CallOption) (*ObjectListResponse, error)
	// 获取Object对象.
	// [EN] Gets a object.
	ObjectGet(ctx context.Context, in *ObjectGetRequest, opts ...grpc.CallOption) (*ObjectGetResponse, error)
	// 上传Object对象.
	// [EN] Puts a object.
	ObjectPut(ctx context.Context, in *ObjectPutRequest, opts ...grpc.CallOption) (*ObjectPutResponse, error)
	// 删除Object对象.
	// [EN] Deletes object.
	ObjectDelete(ctx context.Context, in *ObjectDeleteRequest, opts ...grpc.CallOption) (*ObjectDeleteResponse, error)
	// 获取指定Object对象的预下载地址.
	// [EN] Gets the pre-download url of the specified object.
	ObjectPresignedDownloadUrl(ctx context.Context, in *ObjectPresignedDownloadUrlRequest, opts ...grpc.CallOption) (*ObjectPresignedDownloadUrlResponse, error)
	// 获取指定Object对象的预上传地址.
	// [EN] Gets the pre-upload url of the specified object.
	ObjectPresignedUploadUrl(ctx context.Context, in *ObjectPresignedUploadUrlRequest, opts ...grpc.CallOption) (*ObjectPresignedUploadUrlResponse, error)
	// 安装 [SINCE v0.1.0].
	// [EN] Install [SINCE v0.1.0].
	Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (*InstallResponse, error)
	// Endpoints [SINCE v0.1.0].
	// [EN] Endpoints [SINCE v0.1.0].
	Endpoints(ctx context.Context, in *EndpointsRequest, opts ...grpc.CallOption) (*EndpointsResponse, error)
	// 发送验证码 [SINCE v0.1.0].
	// [EN] Send verification code [SINCE v0.1.0].
	SendCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*SendCodeResponse, error)
	// 注册检查 [SINCE v0.1.0].
	// [EN] Register check [SINCE v0.1.0].
	RegisterCheck(ctx context.Context, in *RegisterCheckRequest, opts ...grpc.CallOption) (*RegisterCheckResponse, error)
	// 注册用户 [SINCE v0.1.0].
	// [EN] Register a user [SINCE v0.1.0].
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 用户登录 [SINCE v0.1.0].
	// [EN] User login [SINCE v0.1.0].
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// 刷新Token [SINCE v0.1.0].
	// [EN] Refresh token [SINCE v0.1.0].
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	// 资源授权检查 [SINCE v0.1.0].
	// [EN] Authorities resource authorization check [SINCE v0.1.0].
	Authorities(ctx context.Context, in *AuthoritiesRequest, opts ...grpc.CallOption) (*AuthoritiesResponse, error)
	// 用户信息 [SINCE v0.1.0].
	// [EN] User info [SINCE v0.1.0].
	UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	// 获取用户的菜单树 [SINCE v0.1.0].
	// [EN] Get the user's menu tree [SINCE v0.1.0].
	UserMenusTree(ctx context.Context, in *UserMenusTreeRequest, opts ...grpc.CallOption) (*UserMenusTreeResponse, error)
	// 用户登出 [SINCE v0.1.0].
	// [EN] User logout [SINCE v0.1.0].
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// 列出用户列表 [SINCE v0.1.0].
	// [EN] List users [SINCE v0.1.0].
	UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	// 获取指定用户 [SINCE v0.1.0].
	// [EN] Get the specified user information [SINCE v0.1.0].
	UserGet(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error)
	// 创建用户 [SINCE v0.1.0].
	// [EN] Create a user [SINCE v0.1.0].
	UserNew(ctx context.Context, in *UserNewRequest, opts ...grpc.CallOption) (*UserNewResponse, error)
	// 删除指定用户 [SINCE v0.1.0].
	// [EN] Delete user [SINCE v0.1.0].
	UserDelete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error)
	// 更新指定用户信息 [SINCE v0.1.0].
	// [EN] Update information of the specified user [SINCE v0.1.0].
	UserUpdate(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*UserUpdateResponse, error)
	// 修改用户密码 [SINCE v0.1.0].
	// [EN] Change user password [SINCE v0.1.0].
	UserChangePassword(ctx context.Context, in *UserChangePasswordRequest, opts ...grpc.CallOption) (*UserChangePasswordResponse, error)
	// 重置用户密码 [SINCE v0.1.0].
	// [EN] Reset user password [SINCE v0.1.0].
	UserResetPassword(ctx context.Context, in *UserResetPasswordRequest, opts ...grpc.CallOption) (*UserResetPasswordResponse, error)
	// 创建角色 [SINCE v0.1.0].
	// [EN] Create a role [SINCE v0.1.0].
	RoleNew(ctx context.Context, in *RoleNewRequest, opts ...grpc.CallOption) (*RoleNewResponse, error)
	// 列出角色列表 [SINCE v0.1.0].
	// [EN] List roles [SINCE v0.1.0].
	RoleList(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListResponse, error)
	// 获取指定角色 [SINCE v0.1.0].
	// [EN] Get the specified role information [SINCE v0.1.0].
	RoleGet(ctx context.Context, in *RoleGetRequest, opts ...grpc.CallOption) (*RoleGetResponse, error)
	// 更新指定角色信息 [SINCE v0.1.0].
	// [EN] Update information of the specified role [SINCE v0.1.0].
	RoleUpdate(ctx context.Context, in *RoleUpdateRequest, opts ...grpc.CallOption) (*RoleUpdateResponse, error)
	// 删除指定角色 [SINCE v0.1.0].
	// [EN] Delete role [SINCE v0.1.0].
	RoleDelete(ctx context.Context, in *RoleDeleteRequest, opts ...grpc.CallOption) (*RoleDeleteResponse, error)
	// 创建菜单 [SINCE v0.1.0].
	// [EN] Create a menu [SINCE v0.1.0].
	MenuNew(ctx context.Context, in *MenuNewRequest, opts ...grpc.CallOption) (*MenuNewResponse, error)
	// 列出菜单列表 [SINCE v0.1.0].
	// [EN] List menus [SINCE v0.1.0].
	MenuList(ctx context.Context, in *MenuListRequest, opts ...grpc.CallOption) (*MenuListResponse, error)
	// 树形菜单列表 [SINCE v0.1.0].
	// [EN] Tree menus [SINCE v0.1.0].
	MenuTree(ctx context.Context, in *MenuTreeRequest, opts ...grpc.CallOption) (*MenuTreeResponse, error)
	// 获取指定菜单 [SINCE v0.1.0].
	// [EN] Get the specified menu information [SINCE v0.1.0].
	MenuGet(ctx context.Context, in *MenuGetRequest, opts ...grpc.CallOption) (*MenuGetResponse, error)
	// 更新指定菜单信息 [SINCE v0.1.0].
	// [EN] Update information of the specified menu [SINCE v0.1.0].
	MenuUpdate(ctx context.Context, in *MenuUpdateRequest, opts ...grpc.CallOption) (*MenuUpdateResponse, error)
	// 删除指定菜单 [SINCE v0.1.0].
	// [EN] Delete menu [SINCE v0.1.0].
	MenuDelete(ctx context.Context, in *MenuDeleteRequest, opts ...grpc.CallOption) (*MenuDeleteResponse, error)
}

type accessControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessControlServiceClient(cc grpc.ClientConnInterface) AccessControlServiceClient {
	return &accessControlServiceClient{cc}
}

func (c *accessControlServiceClient) DictNew(ctx context.Context, in *DictNewRequest, opts ...grpc.CallOption) (*DictNewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictNewResponse)
	err := c.cc.Invoke(ctx, AccessControlService_DictNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) DictList(ctx context.Context, in *DictListRequest, opts ...grpc.CallOption) (*DictListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictListResponse)
	err := c.cc.Invoke(ctx, AccessControlService_DictList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) DictGet(ctx context.Context, in *DictGetRequest, opts ...grpc.CallOption) (*DictGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictGetResponse)
	err := c.cc.Invoke(ctx, AccessControlService_DictGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) DictUpdate(ctx context.Context, in *DictUpdateRequest, opts ...grpc.CallOption) (*DictUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictUpdateResponse)
	err := c.cc.Invoke(ctx, AccessControlService_DictUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) DictDelete(ctx context.Context, in *DictDeleteRequest, opts ...grpc.CallOption) (*DictDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictDeleteResponse)
	err := c.cc.Invoke(ctx, AccessControlService_DictDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) OplogNew(ctx context.Context, in *OplogNewRequest, opts ...grpc.CallOption) (*OplogNewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OplogNewResponse)
	err := c.cc.Invoke(ctx, AccessControlService_OplogNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) OplogList(ctx context.Context, in *OplogListRequest, opts ...grpc.CallOption) (*OplogListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OplogListResponse)
	err := c.cc.Invoke(ctx, AccessControlService_OplogList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) OplogGet(ctx context.Context, in *OplogGetRequest, opts ...grpc.CallOption) (*OplogGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OplogGetResponse)
	err := c.cc.Invoke(ctx, AccessControlService_OplogGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) OplogDelete(ctx context.Context, in *OplogDeleteRequest, opts ...grpc.CallOption) (*OplogDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OplogDeleteResponse)
	err := c.cc.Invoke(ctx, AccessControlService_OplogDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) BucketList(ctx context.Context, in *BucketListRequest, opts ...grpc.CallOption) (*BucketListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BucketListResponse)
	err := c.cc.Invoke(ctx, AccessControlService_BucketList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) BucketNew(ctx context.Context, in *BucketNewRequest, opts ...grpc.CallOption) (*BucketNewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BucketNewResponse)
	err := c.cc.Invoke(ctx, AccessControlService_BucketNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) BucketDelete(ctx context.Context, in *BucketDeleteRequest, opts ...grpc.CallOption) (*BucketDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BucketDeleteResponse)
	err := c.cc.Invoke(ctx, AccessControlService_BucketDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) ObjectList(ctx context.Context, in *ObjectListRequest, opts ...grpc.CallOption) (*ObjectListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectListResponse)
	err := c.cc.Invoke(ctx, AccessControlService_ObjectList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) ObjectGet(ctx context.Context, in *ObjectGetRequest, opts ...grpc.CallOption) (*ObjectGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectGetResponse)
	err := c.cc.Invoke(ctx, AccessControlService_ObjectGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) ObjectPut(ctx context.Context, in *ObjectPutRequest, opts ...grpc.CallOption) (*ObjectPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectPutResponse)
	err := c.cc.Invoke(ctx, AccessControlService_ObjectPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) ObjectDelete(ctx context.Context, in *ObjectDeleteRequest, opts ...grpc.CallOption) (*ObjectDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectDeleteResponse)
	err := c.cc.Invoke(ctx, AccessControlService_ObjectDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) ObjectPresignedDownloadUrl(ctx context.Context, in *ObjectPresignedDownloadUrlRequest, opts ...grpc.CallOption) (*ObjectPresignedDownloadUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectPresignedDownloadUrlResponse)
	err := c.cc.Invoke(ctx, AccessControlService_ObjectPresignedDownloadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) ObjectPresignedUploadUrl(ctx context.Context, in *ObjectPresignedUploadUrlRequest, opts ...grpc.CallOption) (*ObjectPresignedUploadUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectPresignedUploadUrlResponse)
	err := c.cc.Invoke(ctx, AccessControlService_ObjectPresignedUploadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (*InstallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallResponse)
	err := c.cc.Invoke(ctx, AccessControlService_Install_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) Endpoints(ctx context.Context, in *EndpointsRequest, opts ...grpc.CallOption) (*EndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndpointsResponse)
	err := c.cc.Invoke(ctx, AccessControlService_Endpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) SendCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*SendCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCodeResponse)
	err := c.cc.Invoke(ctx, AccessControlService_SendCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) RegisterCheck(ctx context.Context, in *RegisterCheckRequest, opts ...grpc.CallOption) (*RegisterCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCheckResponse)
	err := c.cc.Invoke(ctx, AccessControlService_RegisterCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AccessControlService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AccessControlService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, AccessControlService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) Authorities(ctx context.Context, in *AuthoritiesRequest, opts ...grpc.CallOption) (*AuthoritiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthoritiesResponse)
	err := c.cc.Invoke(ctx, AccessControlService_Authorities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, AccessControlService_UserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) UserMenusTree(ctx context.Context, in *UserMenusTreeRequest, opts ...grpc.CallOption) (*UserMenusTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserMenusTreeResponse)
	err := c.cc.Invoke(ctx, AccessControlService_UserMenusTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AccessControlService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, AccessControlService_UserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) UserGet(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetResponse)
	err := c.cc.Invoke(ctx, AccessControlService_UserGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) UserNew(ctx context.Context, in *UserNewRequest, opts ...grpc.CallOption) (*UserNewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserNewResponse)
	err := c.cc.Invoke(ctx, AccessControlService_UserNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) UserDelete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDeleteResponse)
	err := c.cc.Invoke(ctx, AccessControlService_UserDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) UserUpdate(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*UserUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUpdateResponse)
	err := c.cc.Invoke(ctx, AccessControlService_UserUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) UserChangePassword(ctx context.Context, in *UserChangePasswordRequest, opts ...grpc.CallOption) (*UserChangePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserChangePasswordResponse)
	err := c.cc.Invoke(ctx, AccessControlService_UserChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) UserResetPassword(ctx context.Context, in *UserResetPasswordRequest, opts ...grpc.CallOption) (*UserResetPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResetPasswordResponse)
	err := c.cc.Invoke(ctx, AccessControlService_UserResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) RoleNew(ctx context.Context, in *RoleNewRequest, opts ...grpc.CallOption) (*RoleNewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleNewResponse)
	err := c.cc.Invoke(ctx, AccessControlService_RoleNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) RoleList(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleListResponse)
	err := c.cc.Invoke(ctx, AccessControlService_RoleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) RoleGet(ctx context.Context, in *RoleGetRequest, opts ...grpc.CallOption) (*RoleGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleGetResponse)
	err := c.cc.Invoke(ctx, AccessControlService_RoleGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) RoleUpdate(ctx context.Context, in *RoleUpdateRequest, opts ...grpc.CallOption) (*RoleUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleUpdateResponse)
	err := c.cc.Invoke(ctx, AccessControlService_RoleUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) RoleDelete(ctx context.Context, in *RoleDeleteRequest, opts ...grpc.CallOption) (*RoleDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleDeleteResponse)
	err := c.cc.Invoke(ctx, AccessControlService_RoleDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) MenuNew(ctx context.Context, in *MenuNewRequest, opts ...grpc.CallOption) (*MenuNewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuNewResponse)
	err := c.cc.Invoke(ctx, AccessControlService_MenuNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) MenuList(ctx context.Context, in *MenuListRequest, opts ...grpc.CallOption) (*MenuListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuListResponse)
	err := c.cc.Invoke(ctx, AccessControlService_MenuList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) MenuTree(ctx context.Context, in *MenuTreeRequest, opts ...grpc.CallOption) (*MenuTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuTreeResponse)
	err := c.cc.Invoke(ctx, AccessControlService_MenuTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) MenuGet(ctx context.Context, in *MenuGetRequest, opts ...grpc.CallOption) (*MenuGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuGetResponse)
	err := c.cc.Invoke(ctx, AccessControlService_MenuGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) MenuUpdate(ctx context.Context, in *MenuUpdateRequest, opts ...grpc.CallOption) (*MenuUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuUpdateResponse)
	err := c.cc.Invoke(ctx, AccessControlService_MenuUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlServiceClient) MenuDelete(ctx context.Context, in *MenuDeleteRequest, opts ...grpc.CallOption) (*MenuDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuDeleteResponse)
	err := c.cc.Invoke(ctx, AccessControlService_MenuDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessControlServiceServer is the server API for AccessControlService service.
// All implementations must embed UnimplementedAccessControlServiceServer
// for forward compatibility.
type AccessControlServiceServer interface {
	// 创建字典 [SINCE v0.1.0].
	// [EN] Create a dict [SINCE v0.1.0].
	DictNew(context.Context, *DictNewRequest) (*DictNewResponse, error)
	// 列出字典列表 [SINCE v0.1.0].
	// [EN] List dicts [SINCE v0.1.0].
	DictList(context.Context, *DictListRequest) (*DictListResponse, error)
	// 获取指定字典 [SINCE v0.1.0].
	// [EN] Get the specified dict information [SINCE v0.1.0].
	DictGet(context.Context, *DictGetRequest) (*DictGetResponse, error)
	// 更新指定字典信息 [SINCE v0.1.0].
	// [EN] Update information of the specified dict [SINCE v0.1.0].
	DictUpdate(context.Context, *DictUpdateRequest) (*DictUpdateResponse, error)
	// 删除指定字典 [SINCE v0.1.0].
	// [EN] Delete dict [SINCE v0.1.0].
	DictDelete(context.Context, *DictDeleteRequest) (*DictDeleteResponse, error)
	// 写入操作日志 [SINCE v0.1.0].
	// [EN] Write operation log [SINCE v0.1.0].
	OplogNew(context.Context, *OplogNewRequest) (*OplogNewResponse, error)
	// 列出操作日志列表 [SINCE v0.1.0].
	// [EN] Lists operation log list [SINCE v0.1.0].
	OplogList(context.Context, *OplogListRequest) (*OplogListResponse, error)
	// 获取指定操作日志信息 [SINCE v0.1.0].
	// [EN] Gets specified operation log information [SINCE v0.1.0].
	OplogGet(context.Context, *OplogGetRequest) (*OplogGetResponse, error)
	// 删除指定操作日志 [SINCE v0.1.0].
	// [EN] Delete oplog [SINCE v0.1.0].
	OplogDelete(context.Context, *OplogDeleteRequest) (*OplogDeleteResponse, error)
	// 列出当前所有Bucket空间.
	// [EN] Lists all current Bucket Spaces.
	BucketList(context.Context, *BucketListRequest) (*BucketListResponse, error)
	// 创建Bucket空间.
	// [EN] Deletes bucket.
	BucketNew(context.Context, *BucketNewRequest) (*BucketNewResponse, error)
	// 删除Bucket空间.
	// [EN] Deletes bucket.
	BucketDelete(context.Context, *BucketDeleteRequest) (*BucketDeleteResponse, error)
	// 列出Object对象列表.
	// [EN] Lists objects.
	ObjectList(context.Context, *ObjectListRequest) (*ObjectListResponse, error)
	// 获取Object对象.
	// [EN] Gets a object.
	ObjectGet(context.Context, *ObjectGetRequest) (*ObjectGetResponse, error)
	// 上传Object对象.
	// [EN] Puts a object.
	ObjectPut(context.Context, *ObjectPutRequest) (*ObjectPutResponse, error)
	// 删除Object对象.
	// [EN] Deletes object.
	ObjectDelete(context.Context, *ObjectDeleteRequest) (*ObjectDeleteResponse, error)
	// 获取指定Object对象的预下载地址.
	// [EN] Gets the pre-download url of the specified object.
	ObjectPresignedDownloadUrl(context.Context, *ObjectPresignedDownloadUrlRequest) (*ObjectPresignedDownloadUrlResponse, error)
	// 获取指定Object对象的预上传地址.
	// [EN] Gets the pre-upload url of the specified object.
	ObjectPresignedUploadUrl(context.Context, *ObjectPresignedUploadUrlRequest) (*ObjectPresignedUploadUrlResponse, error)
	// 安装 [SINCE v0.1.0].
	// [EN] Install [SINCE v0.1.0].
	Install(context.Context, *InstallRequest) (*InstallResponse, error)
	// Endpoints [SINCE v0.1.0].
	// [EN] Endpoints [SINCE v0.1.0].
	Endpoints(context.Context, *EndpointsRequest) (*EndpointsResponse, error)
	// 发送验证码 [SINCE v0.1.0].
	// [EN] Send verification code [SINCE v0.1.0].
	SendCode(context.Context, *SendCodeRequest) (*SendCodeResponse, error)
	// 注册检查 [SINCE v0.1.0].
	// [EN] Register check [SINCE v0.1.0].
	RegisterCheck(context.Context, *RegisterCheckRequest) (*RegisterCheckResponse, error)
	// 注册用户 [SINCE v0.1.0].
	// [EN] Register a user [SINCE v0.1.0].
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 用户登录 [SINCE v0.1.0].
	// [EN] User login [SINCE v0.1.0].
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// 刷新Token [SINCE v0.1.0].
	// [EN] Refresh token [SINCE v0.1.0].
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// 资源授权检查 [SINCE v0.1.0].
	// [EN] Authorities resource authorization check [SINCE v0.1.0].
	Authorities(context.Context, *AuthoritiesRequest) (*AuthoritiesResponse, error)
	// 用户信息 [SINCE v0.1.0].
	// [EN] User info [SINCE v0.1.0].
	UserInfo(context.Context, *UserInfoRequest) (*UserInfoResponse, error)
	// 获取用户的菜单树 [SINCE v0.1.0].
	// [EN] Get the user's menu tree [SINCE v0.1.0].
	UserMenusTree(context.Context, *UserMenusTreeRequest) (*UserMenusTreeResponse, error)
	// 用户登出 [SINCE v0.1.0].
	// [EN] User logout [SINCE v0.1.0].
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// 列出用户列表 [SINCE v0.1.0].
	// [EN] List users [SINCE v0.1.0].
	UserList(context.Context, *UserListRequest) (*UserListResponse, error)
	// 获取指定用户 [SINCE v0.1.0].
	// [EN] Get the specified user information [SINCE v0.1.0].
	UserGet(context.Context, *UserGetRequest) (*UserGetResponse, error)
	// 创建用户 [SINCE v0.1.0].
	// [EN] Create a user [SINCE v0.1.0].
	UserNew(context.Context, *UserNewRequest) (*UserNewResponse, error)
	// 删除指定用户 [SINCE v0.1.0].
	// [EN] Delete user [SINCE v0.1.0].
	UserDelete(context.Context, *UserDeleteRequest) (*UserDeleteResponse, error)
	// 更新指定用户信息 [SINCE v0.1.0].
	// [EN] Update information of the specified user [SINCE v0.1.0].
	UserUpdate(context.Context, *UserUpdateRequest) (*UserUpdateResponse, error)
	// 修改用户密码 [SINCE v0.1.0].
	// [EN] Change user password [SINCE v0.1.0].
	UserChangePassword(context.Context, *UserChangePasswordRequest) (*UserChangePasswordResponse, error)
	// 重置用户密码 [SINCE v0.1.0].
	// [EN] Reset user password [SINCE v0.1.0].
	UserResetPassword(context.Context, *UserResetPasswordRequest) (*UserResetPasswordResponse, error)
	// 创建角色 [SINCE v0.1.0].
	// [EN] Create a role [SINCE v0.1.0].
	RoleNew(context.Context, *RoleNewRequest) (*RoleNewResponse, error)
	// 列出角色列表 [SINCE v0.1.0].
	// [EN] List roles [SINCE v0.1.0].
	RoleList(context.Context, *RoleListRequest) (*RoleListResponse, error)
	// 获取指定角色 [SINCE v0.1.0].
	// [EN] Get the specified role information [SINCE v0.1.0].
	RoleGet(context.Context, *RoleGetRequest) (*RoleGetResponse, error)
	// 更新指定角色信息 [SINCE v0.1.0].
	// [EN] Update information of the specified role [SINCE v0.1.0].
	RoleUpdate(context.Context, *RoleUpdateRequest) (*RoleUpdateResponse, error)
	// 删除指定角色 [SINCE v0.1.0].
	// [EN] Delete role [SINCE v0.1.0].
	RoleDelete(context.Context, *RoleDeleteRequest) (*RoleDeleteResponse, error)
	// 创建菜单 [SINCE v0.1.0].
	// [EN] Create a menu [SINCE v0.1.0].
	MenuNew(context.Context, *MenuNewRequest) (*MenuNewResponse, error)
	// 列出菜单列表 [SINCE v0.1.0].
	// [EN] List menus [SINCE v0.1.0].
	MenuList(context.Context, *MenuListRequest) (*MenuListResponse, error)
	// 树形菜单列表 [SINCE v0.1.0].
	// [EN] Tree menus [SINCE v0.1.0].
	MenuTree(context.Context, *MenuTreeRequest) (*MenuTreeResponse, error)
	// 获取指定菜单 [SINCE v0.1.0].
	// [EN] Get the specified menu information [SINCE v0.1.0].
	MenuGet(context.Context, *MenuGetRequest) (*MenuGetResponse, error)
	// 更新指定菜单信息 [SINCE v0.1.0].
	// [EN] Update information of the specified menu [SINCE v0.1.0].
	MenuUpdate(context.Context, *MenuUpdateRequest) (*MenuUpdateResponse, error)
	// 删除指定菜单 [SINCE v0.1.0].
	// [EN] Delete menu [SINCE v0.1.0].
	MenuDelete(context.Context, *MenuDeleteRequest) (*MenuDeleteResponse, error)
	mustEmbedUnimplementedAccessControlServiceServer()
}

// UnimplementedAccessControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessControlServiceServer struct{}

func (UnimplementedAccessControlServiceServer) DictNew(context.Context, *DictNewRequest) (*DictNewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictNew not implemented")
}
func (UnimplementedAccessControlServiceServer) DictList(context.Context, *DictListRequest) (*DictListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictList not implemented")
}
func (UnimplementedAccessControlServiceServer) DictGet(context.Context, *DictGetRequest) (*DictGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictGet not implemented")
}
func (UnimplementedAccessControlServiceServer) DictUpdate(context.Context, *DictUpdateRequest) (*DictUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictUpdate not implemented")
}
func (UnimplementedAccessControlServiceServer) DictDelete(context.Context, *DictDeleteRequest) (*DictDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictDelete not implemented")
}
func (UnimplementedAccessControlServiceServer) OplogNew(context.Context, *OplogNewRequest) (*OplogNewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OplogNew not implemented")
}
func (UnimplementedAccessControlServiceServer) OplogList(context.Context, *OplogListRequest) (*OplogListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OplogList not implemented")
}
func (UnimplementedAccessControlServiceServer) OplogGet(context.Context, *OplogGetRequest) (*OplogGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OplogGet not implemented")
}
func (UnimplementedAccessControlServiceServer) OplogDelete(context.Context, *OplogDeleteRequest) (*OplogDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OplogDelete not implemented")
}
func (UnimplementedAccessControlServiceServer) BucketList(context.Context, *BucketListRequest) (*BucketListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketList not implemented")
}
func (UnimplementedAccessControlServiceServer) BucketNew(context.Context, *BucketNewRequest) (*BucketNewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketNew not implemented")
}
func (UnimplementedAccessControlServiceServer) BucketDelete(context.Context, *BucketDeleteRequest) (*BucketDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketDelete not implemented")
}
func (UnimplementedAccessControlServiceServer) ObjectList(context.Context, *ObjectListRequest) (*ObjectListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObjectList not implemented")
}
func (UnimplementedAccessControlServiceServer) ObjectGet(context.Context, *ObjectGetRequest) (*ObjectGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObjectGet not implemented")
}
func (UnimplementedAccessControlServiceServer) ObjectPut(context.Context, *ObjectPutRequest) (*ObjectPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObjectPut not implemented")
}
func (UnimplementedAccessControlServiceServer) ObjectDelete(context.Context, *ObjectDeleteRequest) (*ObjectDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObjectDelete not implemented")
}
func (UnimplementedAccessControlServiceServer) ObjectPresignedDownloadUrl(context.Context, *ObjectPresignedDownloadUrlRequest) (*ObjectPresignedDownloadUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObjectPresignedDownloadUrl not implemented")
}
func (UnimplementedAccessControlServiceServer) ObjectPresignedUploadUrl(context.Context, *ObjectPresignedUploadUrlRequest) (*ObjectPresignedUploadUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObjectPresignedUploadUrl not implemented")
}
func (UnimplementedAccessControlServiceServer) Install(context.Context, *InstallRequest) (*InstallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Install not implemented")
}
func (UnimplementedAccessControlServiceServer) Endpoints(context.Context, *EndpointsRequest) (*EndpointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Endpoints not implemented")
}
func (UnimplementedAccessControlServiceServer) SendCode(context.Context, *SendCodeRequest) (*SendCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCode not implemented")
}
func (UnimplementedAccessControlServiceServer) RegisterCheck(context.Context, *RegisterCheckRequest) (*RegisterCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCheck not implemented")
}
func (UnimplementedAccessControlServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAccessControlServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAccessControlServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAccessControlServiceServer) Authorities(context.Context, *AuthoritiesRequest) (*AuthoritiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorities not implemented")
}
func (UnimplementedAccessControlServiceServer) UserInfo(context.Context, *UserInfoRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (UnimplementedAccessControlServiceServer) UserMenusTree(context.Context, *UserMenusTreeRequest) (*UserMenusTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMenusTree not implemented")
}
func (UnimplementedAccessControlServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAccessControlServiceServer) UserList(context.Context, *UserListRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (UnimplementedAccessControlServiceServer) UserGet(context.Context, *UserGetRequest) (*UserGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGet not implemented")
}
func (UnimplementedAccessControlServiceServer) UserNew(context.Context, *UserNewRequest) (*UserNewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserNew not implemented")
}
func (UnimplementedAccessControlServiceServer) UserDelete(context.Context, *UserDeleteRequest) (*UserDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDelete not implemented")
}
func (UnimplementedAccessControlServiceServer) UserUpdate(context.Context, *UserUpdateRequest) (*UserUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUpdate not implemented")
}
func (UnimplementedAccessControlServiceServer) UserChangePassword(context.Context, *UserChangePasswordRequest) (*UserChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserChangePassword not implemented")
}
func (UnimplementedAccessControlServiceServer) UserResetPassword(context.Context, *UserResetPasswordRequest) (*UserResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserResetPassword not implemented")
}
func (UnimplementedAccessControlServiceServer) RoleNew(context.Context, *RoleNewRequest) (*RoleNewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoleNew not implemented")
}
func (UnimplementedAccessControlServiceServer) RoleList(context.Context, *RoleListRequest) (*RoleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoleList not implemented")
}
func (UnimplementedAccessControlServiceServer) RoleGet(context.Context, *RoleGetRequest) (*RoleGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoleGet not implemented")
}
func (UnimplementedAccessControlServiceServer) RoleUpdate(context.Context, *RoleUpdateRequest) (*RoleUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoleUpdate not implemented")
}
func (UnimplementedAccessControlServiceServer) RoleDelete(context.Context, *RoleDeleteRequest) (*RoleDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoleDelete not implemented")
}
func (UnimplementedAccessControlServiceServer) MenuNew(context.Context, *MenuNewRequest) (*MenuNewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MenuNew not implemented")
}
func (UnimplementedAccessControlServiceServer) MenuList(context.Context, *MenuListRequest) (*MenuListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MenuList not implemented")
}
func (UnimplementedAccessControlServiceServer) MenuTree(context.Context, *MenuTreeRequest) (*MenuTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MenuTree not implemented")
}
func (UnimplementedAccessControlServiceServer) MenuGet(context.Context, *MenuGetRequest) (*MenuGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MenuGet not implemented")
}
func (UnimplementedAccessControlServiceServer) MenuUpdate(context.Context, *MenuUpdateRequest) (*MenuUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MenuUpdate not implemented")
}
func (UnimplementedAccessControlServiceServer) MenuDelete(context.Context, *MenuDeleteRequest) (*MenuDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MenuDelete not implemented")
}
func (UnimplementedAccessControlServiceServer) mustEmbedUnimplementedAccessControlServiceServer() {}
func (UnimplementedAccessControlServiceServer) testEmbeddedByValue()                              {}

// UnsafeAccessControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessControlServiceServer will
// result in compilation errors.
type UnsafeAccessControlServiceServer interface {
	mustEmbedUnimplementedAccessControlServiceServer()
}

func RegisterAccessControlServiceServer(s grpc.ServiceRegistrar, srv AccessControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccessControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessControlService_ServiceDesc, srv)
}

func _AccessControlService_DictNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).DictNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_DictNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).DictNew(ctx, req.(*DictNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_DictList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).DictList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_DictList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).DictList(ctx, req.(*DictListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_DictGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).DictGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_DictGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).DictGet(ctx, req.(*DictGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_DictUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).DictUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_DictUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).DictUpdate(ctx, req.(*DictUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_DictDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).DictDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_DictDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).DictDelete(ctx, req.(*DictDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_OplogNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OplogNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).OplogNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_OplogNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).OplogNew(ctx, req.(*OplogNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_OplogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OplogListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).OplogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_OplogList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).OplogList(ctx, req.(*OplogListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_OplogGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OplogGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).OplogGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_OplogGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).OplogGet(ctx, req.(*OplogGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_OplogDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OplogDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).OplogDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_OplogDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).OplogDelete(ctx, req.(*OplogDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_BucketList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).BucketList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_BucketList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).BucketList(ctx, req.(*BucketListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_BucketNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).BucketNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_BucketNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).BucketNew(ctx, req.(*BucketNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_BucketDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).BucketDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_BucketDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).BucketDelete(ctx, req.(*BucketDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_ObjectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).ObjectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_ObjectList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).ObjectList(ctx, req.(*ObjectListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_ObjectGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).ObjectGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_ObjectGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).ObjectGet(ctx, req.(*ObjectGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_ObjectPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).ObjectPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_ObjectPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).ObjectPut(ctx, req.(*ObjectPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_ObjectDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).ObjectDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_ObjectDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).ObjectDelete(ctx, req.(*ObjectDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_ObjectPresignedDownloadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectPresignedDownloadUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).ObjectPresignedDownloadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_ObjectPresignedDownloadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).ObjectPresignedDownloadUrl(ctx, req.(*ObjectPresignedDownloadUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_ObjectPresignedUploadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectPresignedUploadUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).ObjectPresignedUploadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_ObjectPresignedUploadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).ObjectPresignedUploadUrl(ctx, req.(*ObjectPresignedUploadUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_Install_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).Install(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_Install_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).Install(ctx, req.(*InstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_Endpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).Endpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_Endpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).Endpoints(ctx, req.(*EndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_SendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).SendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_SendCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).SendCode(ctx, req.(*SendCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_RegisterCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).RegisterCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_RegisterCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).RegisterCheck(ctx, req.(*RegisterCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_Authorities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthoritiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).Authorities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_Authorities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).Authorities(ctx, req.(*AuthoritiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_UserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).UserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_UserMenusTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMenusTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).UserMenusTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_UserMenusTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).UserMenusTree(ctx, req.(*UserMenusTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_UserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).UserList(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_UserGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).UserGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_UserGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).UserGet(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_UserNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).UserNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_UserNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).UserNew(ctx, req.(*UserNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_UserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).UserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_UserDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).UserDelete(ctx, req.(*UserDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_UserUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).UserUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_UserUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).UserUpdate(ctx, req.(*UserUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_UserChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).UserChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_UserChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).UserChangePassword(ctx, req.(*UserChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_UserResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).UserResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_UserResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).UserResetPassword(ctx, req.(*UserResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_RoleNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).RoleNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_RoleNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).RoleNew(ctx, req.(*RoleNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_RoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).RoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_RoleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).RoleList(ctx, req.(*RoleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_RoleGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).RoleGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_RoleGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).RoleGet(ctx, req.(*RoleGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_RoleUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).RoleUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_RoleUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).RoleUpdate(ctx, req.(*RoleUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_RoleDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).RoleDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_RoleDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).RoleDelete(ctx, req.(*RoleDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_MenuNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).MenuNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_MenuNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).MenuNew(ctx, req.(*MenuNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_MenuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).MenuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_MenuList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).MenuList(ctx, req.(*MenuListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_MenuTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).MenuTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_MenuTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).MenuTree(ctx, req.(*MenuTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_MenuGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).MenuGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_MenuGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).MenuGet(ctx, req.(*MenuGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_MenuUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).MenuUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_MenuUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).MenuUpdate(ctx, req.(*MenuUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControlService_MenuDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).MenuDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_MenuDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).MenuDelete(ctx, req.(*MenuDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessControlService_ServiceDesc is the grpc.ServiceDesc for AccessControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ddv.access_control.api.AccessControlService",
	HandlerType: (*AccessControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DictNew",
			Handler:    _AccessControlService_DictNew_Handler,
		},
		{
			MethodName: "DictList",
			Handler:    _AccessControlService_DictList_Handler,
		},
		{
			MethodName: "DictGet",
			Handler:    _AccessControlService_DictGet_Handler,
		},
		{
			MethodName: "DictUpdate",
			Handler:    _AccessControlService_DictUpdate_Handler,
		},
		{
			MethodName: "DictDelete",
			Handler:    _AccessControlService_DictDelete_Handler,
		},
		{
			MethodName: "OplogNew",
			Handler:    _AccessControlService_OplogNew_Handler,
		},
		{
			MethodName: "OplogList",
			Handler:    _AccessControlService_OplogList_Handler,
		},
		{
			MethodName: "OplogGet",
			Handler:    _AccessControlService_OplogGet_Handler,
		},
		{
			MethodName: "OplogDelete",
			Handler:    _AccessControlService_OplogDelete_Handler,
		},
		{
			MethodName: "BucketList",
			Handler:    _AccessControlService_BucketList_Handler,
		},
		{
			MethodName: "BucketNew",
			Handler:    _AccessControlService_BucketNew_Handler,
		},
		{
			MethodName: "BucketDelete",
			Handler:    _AccessControlService_BucketDelete_Handler,
		},
		{
			MethodName: "ObjectList",
			Handler:    _AccessControlService_ObjectList_Handler,
		},
		{
			MethodName: "ObjectGet",
			Handler:    _AccessControlService_ObjectGet_Handler,
		},
		{
			MethodName: "ObjectPut",
			Handler:    _AccessControlService_ObjectPut_Handler,
		},
		{
			MethodName: "ObjectDelete",
			Handler:    _AccessControlService_ObjectDelete_Handler,
		},
		{
			MethodName: "ObjectPresignedDownloadUrl",
			Handler:    _AccessControlService_ObjectPresignedDownloadUrl_Handler,
		},
		{
			MethodName: "ObjectPresignedUploadUrl",
			Handler:    _AccessControlService_ObjectPresignedUploadUrl_Handler,
		},
		{
			MethodName: "Install",
			Handler:    _AccessControlService_Install_Handler,
		},
		{
			MethodName: "Endpoints",
			Handler:    _AccessControlService_Endpoints_Handler,
		},
		{
			MethodName: "SendCode",
			Handler:    _AccessControlService_SendCode_Handler,
		},
		{
			MethodName: "RegisterCheck",
			Handler:    _AccessControlService_RegisterCheck_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AccessControlService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AccessControlService_Login_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AccessControlService_RefreshToken_Handler,
		},
		{
			MethodName: "Authorities",
			Handler:    _AccessControlService_Authorities_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _AccessControlService_UserInfo_Handler,
		},
		{
			MethodName: "UserMenusTree",
			Handler:    _AccessControlService_UserMenusTree_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AccessControlService_Logout_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _AccessControlService_UserList_Handler,
		},
		{
			MethodName: "UserGet",
			Handler:    _AccessControlService_UserGet_Handler,
		},
		{
			MethodName: "UserNew",
			Handler:    _AccessControlService_UserNew_Handler,
		},
		{
			MethodName: "UserDelete",
			Handler:    _AccessControlService_UserDelete_Handler,
		},
		{
			MethodName: "UserUpdate",
			Handler:    _AccessControlService_UserUpdate_Handler,
		},
		{
			MethodName: "UserChangePassword",
			Handler:    _AccessControlService_UserChangePassword_Handler,
		},
		{
			MethodName: "UserResetPassword",
			Handler:    _AccessControlService_UserResetPassword_Handler,
		},
		{
			MethodName: "RoleNew",
			Handler:    _AccessControlService_RoleNew_Handler,
		},
		{
			MethodName: "RoleList",
			Handler:    _AccessControlService_RoleList_Handler,
		},
		{
			MethodName: "RoleGet",
			Handler:    _AccessControlService_RoleGet_Handler,
		},
		{
			MethodName: "RoleUpdate",
			Handler:    _AccessControlService_RoleUpdate_Handler,
		},
		{
			MethodName: "RoleDelete",
			Handler:    _AccessControlService_RoleDelete_Handler,
		},
		{
			MethodName: "MenuNew",
			Handler:    _AccessControlService_MenuNew_Handler,
		},
		{
			MethodName: "MenuList",
			Handler:    _AccessControlService_MenuList_Handler,
		},
		{
			MethodName: "MenuTree",
			Handler:    _AccessControlService_MenuTree_Handler,
		},
		{
			MethodName: "MenuGet",
			Handler:    _AccessControlService_MenuGet_Handler,
		},
		{
			MethodName: "MenuUpdate",
			Handler:    _AccessControlService_MenuUpdate_Handler,
		},
		{
			MethodName: "MenuDelete",
			Handler:    _AccessControlService_MenuDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/Divine-Dragon-Voyage/engine-access-control-service/pb/engine-access-control-service.proto",
}
