// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.3
// source: proto/common.proto

package commonapis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 公共状态码.
// [EN] Common status code.
type StatusCode int32

const (
	// 成功返回.
	// [EN] OK is returned on success.
	StatusCode_OK StatusCode = 0
	// 操作被取消（通常由调用方取消）.
	//
	// 当请求取消时，gRPC框架将生成此错误码.
	// [EN] Canceled indicates the operation was canceled (typically by the caller).
	//
	// The gRPC framework will generate this error code when cancellation
	// is requested.
	StatusCode_Canceled StatusCode = 1
	// 未知错误. 例如，如果从另一个地址空间接收到的Status值属于
	// 此地址空间中未知的错误空间时，可能会返回此错误.
	// 由于没有返回足够错误信息的API引发的错误也可能被转换为此错误.
	//
	// gRPC框架将在上述两种情况下生成此错误码.
	// [EN] Unknown error. An example of where this error may be returned is
	// if a Status value received from another address space belongs to
	// an error-space that is not known in this address space. Also
	// errors raised by APIs that do not return enough error information
	// may be converted to this error.
	//
	// The gRPC framework will generate this error code in the above two
	// mentioned cases.
	StatusCode_Unknown StatusCode = 2
	// 无效参数，表示客户端指定了无效的参数.
	// 请注意，这与FailedPrecondition不同. 它表示无论系统状态如何
	// 都有问题的参数（例如，格式错误的文件名）.
	//
	// gRPC框架不会生成此错误码.
	// [EN] InvalidArgument indicates client specified an invalid argument.
	// Note that this differs from FailedPrecondition. It indicates arguments
	// that are problematic regardless of the state of the system
	// (e.g., a malformed file name).
	//
	// This error code will not be generated by the gRPC framework.
	StatusCode_InvalidArgument StatusCode = 3
	// 截止时间超时，表示操作在完成之前已过期.
	// 对于改变系统状态的操作，即使操作已成功完成，
	// 也可能返回此错误. 例如，来自服务器的成功响应可能
	// 被延迟得足够长，以至于截止时间过期.
	//
	// 当截止时间超过时，gRPC框架将生成此错误码.
	// [EN] DeadlineExceeded means operation expired before completion.
	// For operations that change the state of the system, this error may be
	// returned even if the operation has completed successfully. For
	// example, a successful response from a server could have been delayed
	// long enough for the deadline to expire.
	//
	// The gRPC framework will generate this error code when the deadline is
	// exceeded.
	StatusCode_DeadlineExceeded StatusCode = 4
	// 未找到，表示某些请求的实体（例如，文件或目录）未找到.
	//
	// gRPC框架不会生成此错误码.
	// [EN] NotFound means some requested entity (e.g., file or directory) was
	// not found.
	//
	// This error code will not be generated by the gRPC framework.
	StatusCode_NotFound StatusCode = 5
	// 已存在，表示尝试创建实体失败，因为已经存在.
	//
	// gRPC框架不会生成此错误码.
	// [EN] AlreadyExists means an attempt to create an entity failed because one
	// already exists.
	//
	// This error code will not be generated by the gRPC framework.
	StatusCode_AlreadyExists StatusCode = 6
	// 权限拒绝，表示调用者没有权限执行指定的操作.
	// 不能用于由于资源耗尽而引起的拒绝（对于这些错误请使用ResourceExhausted）.
	// 如果无法识别调用者，则不能使用此代码（对于这些错误请使用Unauthenticated）.
	//
	// gRPC核心框架不会生成此错误码，但期望身份验证中间件使用它.
	// [EN] PermissionDenied indicates the caller does not have permission to
	// execute the specified operation. It must not be used for rejections
	// caused by exhausting some resource (use ResourceExhausted
	// instead for those errors). It must not be
	// used if the caller cannot be identified (use Unauthenticated
	// instead for those errors).
	//
	// This error code will not be generated by the gRPC core framework,
	// but expect authentication middleware to use it.
	StatusCode_PermissionDenied StatusCode = 7
	// 资源耗尽，表示某些资源已用尽，可能是每用户配额，
	// 或者整个文件系统空间不足.
	//
	// 在内存不足和服务器过载情况下，或者当消息大于配置的最大大小时，
	// gRPC框架将生成此错误码.
	// [EN] ResourceExhausted indicates some resource has been exhausted, perhaps
	// a per-user quota, or perhaps the entire file system is out of space.
	//
	// This error code will be generated by the gRPC framework in
	// out-of-memory and server overload situations, or when a message is
	// larger than the configured maximum size.
	StatusCode_ResourceExhausted StatusCode = 8
	// 前提条件失败，表示操作被拒绝，因为系统不处于操作执行所需的状态.
	// 例如，要删除的目录可能为非空，rmdir操作应用于非目录等.
	//
	// 以下测试可能有助于服务实施者在FailedPrecondition、Aborted和Unavailable之间做出决定：
	//
	//	(a) 如果客户端可以重试失败的调用，请使用Unavailable.
	//	(b) 如果客户端应该在更高级别重试（例如，重新启动读-修改-写序列），请使用Aborted.
	//	(c) 如果在系统状态明确修复之前客户端不应重试，请使用FailedPrecondition.
	//	    例如，如果"rmdir"因为目录非空而失败，应该返回FailedPrecondition，
	//	    因为客户端不应重试，除非他们首先通过删除目录中的文件来修复目录.
	//	(d) 如果客户端对资源执行条件REST Get/Update/Delete，
	//	    而服务器上的资源不匹配条件，请使用FailedPrecondition.
	//	    例如，对同一资源进行冲突的读-修改-写操作.
	//
	// gRPC框架不会生成此错误码.
	// [EN] FailedPrecondition indicates operation was rejected because the
	// system is not in a state required for the operation's execution.
	// For example, directory to be deleted may be non-empty, an rmdir
	// operation is applied to a non-directory, etc.
	//
	// A litmus test that may help a service implementor in deciding
	// between FailedPrecondition, Aborted, and Unavailable:
	//
	//	(a) Use Unavailable if the client can retry just the failing call.
	//	(b) Use Aborted if the client should retry at a higher-level
	//	    (e.g., restarting a read-modify-write sequence).
	//	(c) Use FailedPrecondition if the client should not retry until
	//	    the system state has been explicitly fixed. E.g., if an "rmdir"
	//	    fails because the directory is non-empty, FailedPrecondition
	//	    should be returned since the client should not retry unless
	//	    they have first fixed up the directory by deleting files from it.
	//	(d) Use FailedPrecondition if the client performs conditional
	//	    REST Get/Update/Delete on a resource and the resource on the
	//	    server does not match the condition. E.g., conflicting
	//	    read-modify-write on the same resource.
	//
	// This error code will not be generated by the gRPC framework.
	StatusCode_FailedPrecondition StatusCode = 9
	// 中止，表示操作被中止，通常是由于并发问题，
	// 如序列检查失败、事务中止等.
	//
	// 有关在FailedPrecondition、Aborted和Unavailable之间决策的测试，请参见上文.
	//
	// gRPC框架不会生成此错误码.
	// [EN] Aborted indicates the operation was aborted, typically due to a
	// concurrency issue like sequencer check failures, transaction aborts,
	// etc.
	//
	// See litmus test above for deciding between FailedPrecondition,
	// Aborted, and Unavailable.
	//
	// This error code will not be generated by the gRPC framework.
	StatusCode_Aborted StatusCode = 10
	// 超出范围，表示尝试的操作超出了有效范围.
	// 例如，寻找或读取超出文件末尾.
	//
	// 与InvalidArgument不同，此错误表示如果系统状态改变可能会修复的问题.
	// 例如，32位文件系统在被要求读取不在[0,2^32-1]范围内的偏移量时会生成InvalidArgument，
	// 但如果被要求读取超出当前文件大小的偏移量会生成OutOfRange.
	//
	// FailedPrecondition和OutOfRange之间有相当大的重叠.
	// 我们建议在适用时使用OutOfRange（更具体的错误），
	// 以便在空间中迭代的调用者可以轻松寻找OutOfRange错误来检测何时完成.
	//
	// gRPC框架不会生成此错误码.
	// [EN] OutOfRange means operation was attempted past the valid range.
	// E.g., seeking or reading past end of file.
	//
	// Unlike InvalidArgument, this error indicates a problem that may
	// be fixed if the system state changes. For example, a 32-bit file
	// system will generate InvalidArgument if asked to read at an
	// offset that is not in the range [0,2^32-1], but it will generate
	// OutOfRange if asked to read from an offset past the current
	// file size.
	//
	// There is a fair bit of overlap between FailedPrecondition and
	// OutOfRange. We recommend using OutOfRange (the more specific
	// error) when it applies so that callers who are iterating through
	// a space can easily look for an OutOfRange error to detect when
	// they are done.
	//
	// This error code will not be generated by the gRPC framework.
	StatusCode_OutOfRange StatusCode = 11
	// 未实现，表示操作未实现或在此服务中未支持/启用.
	//
	// gRPC框架将生成此错误码. 最常见的情况是，
	// 当服务器上缺少方法实现时，您会看到此错误码.
	// 也可能由于未知的压缩算法或关于RPC是否应该是流式的分歧而生成.
	// [EN] Unimplemented indicates operation is not implemented or not
	// supported/enabled in this service.
	//
	// This error code will be generated by the gRPC framework. Most
	// commonly, you will see this error code when a method implementation
	// is missing on the server. It can also be generated for unknown
	// compression algorithms or a disagreement as to whether an RPC should
	// be streaming.
	StatusCode_Unimplemented StatusCode = 12
	// 内部错误. 表示底层系统预期的某些不变量已被破坏.
	// 如果您看到这些错误之一，说明某些东西严重损坏.
	//
	// gRPC框架将在几种内部错误情况下生成此错误码.
	// [EN] Internal errors. Means some invariants expected by underlying
	// system has been broken. If you see one of these errors,
	// something is very broken.
	//
	// This error code will be generated by the gRPC framework in several
	// internal error conditions.
	StatusCode_Internal StatusCode = 13
	// 不可用，表示服务当前不可用.
	// 这很可能是一个暂时的情况，可以通过退避重试来纠正.
	// 请注意，重试非幂等操作并不总是安全的.
	//
	// 有关在FailedPrecondition、Aborted和Unavailable之间决策的测试，请参见上文.
	//
	// 在服务器进程或网络连接突然关闭期间，gRPC框架将生成此错误码.
	// [EN] Unavailable indicates the service is currently unavailable.
	// This is a most likely a transient condition and may be corrected
	// by retrying with a backoff. Note that it is not always safe to retry
	// non-idempotent operations.
	//
	// See litmus test above for deciding between FailedPrecondition,
	// Aborted, and Unavailable.
	//
	// This error code will be generated by the gRPC framework during
	// abrupt shutdown of a server process or network connection.
	StatusCode_Unavailable StatusCode = 14
	// 数据丢失，表示不可恢复的数据丢失或损坏.
	//
	// gRPC框架不会生成此错误码.
	// [EN] DataLoss indicates unrecoverable data loss or corruption.
	//
	// This error code will not be generated by the gRPC framework.
	StatusCode_DataLoss StatusCode = 15
	// 未认证，表示请求没有用于操作的有效身份验证凭据.
	//
	// 当身份验证元数据无效或Credentials回调失败时，
	// gRPC框架将生成此错误码，但也期望身份验证中间件生成此错误码.
	// [EN] Unauthenticated indicates the request does not have valid
	// authentication credentials for the operation.
	//
	// The gRPC framework will generate this error code when the
	// authentication metadata is invalid or a Credentials callback fails,
	// but also expect authentication middleware to generate it.
	StatusCode_Unauthenticated StatusCode = 16
	// 未知系统错误.
	// [EN] Unknown system error.
	StatusCode_SYSTEM_UNKNOWN_ERROR StatusCode = 101
	// 网络错误.
	// [EN] Network error.
	StatusCode_SYSTEM_NETWORK_ERROR StatusCode = 102
	// 存储系统错误.
	// [EN] Storage system error.
	StatusCode_SYSTEM_STORAGE_ERROR StatusCode = 103
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:   "OK",
		1:   "Canceled",
		2:   "Unknown",
		3:   "InvalidArgument",
		4:   "DeadlineExceeded",
		5:   "NotFound",
		6:   "AlreadyExists",
		7:   "PermissionDenied",
		8:   "ResourceExhausted",
		9:   "FailedPrecondition",
		10:  "Aborted",
		11:  "OutOfRange",
		12:  "Unimplemented",
		13:  "Internal",
		14:  "Unavailable",
		15:  "DataLoss",
		16:  "Unauthenticated",
		101: "SYSTEM_UNKNOWN_ERROR",
		102: "SYSTEM_NETWORK_ERROR",
		103: "SYSTEM_STORAGE_ERROR",
	}
	StatusCode_value = map[string]int32{
		"OK":                   0,
		"Canceled":             1,
		"Unknown":              2,
		"InvalidArgument":      3,
		"DeadlineExceeded":     4,
		"NotFound":             5,
		"AlreadyExists":        6,
		"PermissionDenied":     7,
		"ResourceExhausted":    8,
		"FailedPrecondition":   9,
		"Aborted":              10,
		"OutOfRange":           11,
		"Unimplemented":        12,
		"Internal":             13,
		"Unavailable":          14,
		"DataLoss":             15,
		"Unauthenticated":      16,
		"SYSTEM_UNKNOWN_ERROR": 101,
		"SYSTEM_NETWORK_ERROR": 102,
		"SYSTEM_STORAGE_ERROR": 103,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

// 通用处理结果返回. 通常在Batch类请求中返回每个子请求的错误状态.
// [EN] General processing results returned. Error status of each sub-request is
// usually returned in Batch mode requests.
type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 通用服务、系统错误码, 对应HTTP错误及语义见系统标准错误表.
	// 若为业务特定错误, code应返回0, 详情见status及对应错误.
	// [EN] For common service and system error codes, see the system standard
	// error table corresponding HTTP errors and semantics. For business-specific
	// errors, code will return 0. For details, see status and corresponding
	// errors.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 错误详细描述.
	// [EN] Detailed description of the error.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// 业务错误码.
	// [EN] Business error code.
	Status        StatusCode `protobuf:"varint,3,opt,name=status,proto3,enum=StatusCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Result) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_OK
}

// 通用翻页结构.
// [EN] Common paging structure.
type Paging struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可选, 取值:>=0, 默认值为1.
	// [EN] Optional, start page, value: > = 0, the default value is 1.
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 数量, 默认取值范围[1,100], 如果超出范围, 则返回失败.
	// [EN] Size, default value range [1,100], if it is out of the range, error
	// will be returned.
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// 可选, 请求无须填此参数, 响应时系统填写.
	// [EN] Optional, this parameter is not required for request, but will be
	// filled in response.
	Total         int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paging) Reset() {
	*x = Paging{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paging) ProtoMessage() {}

func (x *Paging) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paging.ProtoReflect.Descriptor instead.
func (*Paging) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *Paging) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Paging) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Paging) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 通用排序结构.
// [EN] Common sorting structure.
type Sorting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 排序字段, 接口对应字段, 由对应接口解析.
	// [EN] Sort field, the corresponding field of the interface, which is parsed
	// by the corresponding interface.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// 可选, 是否倒序
	// [EN] Optional: Reverse order or not
	Reversed      bool `protobuf:"varint,2,opt,name=reversed,proto3" json:"reversed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sorting) Reset() {
	*x = Sorting{}
	mi := &file_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sorting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sorting) ProtoMessage() {}

func (x *Sorting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sorting.ProtoReflect.Descriptor instead.
func (*Sorting) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *Sorting) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Sorting) GetReversed() bool {
	if x != nil {
		return x.Reversed
	}
	return false
}

// TimeRange表示一段时间区间 [start, end) , 时间戳为UTC时间.
// 时间戳JSON表示形式为RFC 3339格式, 如: "1972-01-01T10:00:20.021Z".
// [EN] TimeRange, represents a period of time interval [start, end), which the
// timestamp is UTC time. The representation of JSON timestamp is RFC3339
// format, such as: “1972-01-01T10:00:20.021Z”.
type TimeRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 开始时间, 区间包含.
	// [EN] Start time, interval inclusive.
	Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// 结束时间, 区间不包含.
	// [EN] End time, interval exclusive.
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *TimeRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\x06Result\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\x06status\x18\x03 \x01(\x0e2\v.StatusCodeR\x06status\"F\n" +
	"\x06Paging\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\";\n" +
	"\aSorting\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\breversed\x18\x02 \x01(\bR\breversed\"k\n" +
	"\tTimeRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end*\x8d\x03\n" +
	"\n" +
	"StatusCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\f\n" +
	"\bCanceled\x10\x01\x12\v\n" +
	"\aUnknown\x10\x02\x12\x13\n" +
	"\x0fInvalidArgument\x10\x03\x12\x14\n" +
	"\x10DeadlineExceeded\x10\x04\x12\f\n" +
	"\bNotFound\x10\x05\x12\x11\n" +
	"\rAlreadyExists\x10\x06\x12\x14\n" +
	"\x10PermissionDenied\x10\a\x12\x15\n" +
	"\x11ResourceExhausted\x10\b\x12\x16\n" +
	"\x12FailedPrecondition\x10\t\x12\v\n" +
	"\aAborted\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"OutOfRange\x10\v\x12\x11\n" +
	"\rUnimplemented\x10\f\x12\f\n" +
	"\bInternal\x10\r\x12\x0f\n" +
	"\vUnavailable\x10\x0e\x12\f\n" +
	"\bDataLoss\x10\x0f\x12\x13\n" +
	"\x0fUnauthenticated\x10\x10\x12\x18\n" +
	"\x14SYSTEM_UNKNOWN_ERROR\x10e\x12\x18\n" +
	"\x14SYSTEM_NETWORK_ERROR\x10f\x12\x18\n" +
	"\x14SYSTEM_STORAGE_ERROR\x10g\"\x04\b\x11\x10d\"\x05\bh\x10\xc8\x01BX\n" +
	"\"com.github.kamalyes.commonapis.apiZ2github.com/kamalyes/go-rpc-gateway/pbuf/commonapisb\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_common_proto_goTypes = []any{
	(StatusCode)(0),               // 0: StatusCode
	(*Result)(nil),                // 1: Result
	(*Paging)(nil),                // 2: Paging
	(*Sorting)(nil),               // 3: Sorting
	(*TimeRange)(nil),             // 4: TimeRange
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_common_proto_depIdxs = []int32{
	0, // 0: Result.status:type_name -> StatusCode
	5, // 1: TimeRange.start:type_name -> google.protobuf.Timestamp
	5, // 2: TimeRange.end:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
